const data = [
  {
    id: 1,
    name: "A  Court of Silver",
    image: "./shopping_cart/images_1/court.jpg",
    desc: "A Court of Silver and Flames",
    author: "Sarah J.Maas",
    price: 19.95,
  },
  {
    id: 2,
    name: "Six of Crows",
    image: "./shopping_cart/images_1/Crows.jpg",
    desc: "Six of Crows",
    author: "Leigh Bardugo",
    price: 15.95,
  },
  {
    id: 3,
    name: "Darkdawn",
    image: "./shopping_cart/images_1/Darkdawn.jpg",
    desc: "Darkdawn",
    author: "Jay Kristoff",
    price: 18.75,
  },
  {
    id: 4,
    name: "Earthsea",
    image: "./shopping_cart/images_1/Earthsea.jpg",
    desc: "Earthsea",
    author: "Ursula K. Le Guin ",
    price: 18.28,
  },
  {
    id: 5,
    name: "Fire and Blood",
    image: "./shopping_cart/images_1/GoT.jpg",
    desc: "Fire and Blood",
    author: " George R.R.Martin",
    price: 17.85,
  },
  {
    id: 6,
    name: "The Name of the Wind",
    image: "./shopping_cart/images_1/name.jpg",
    desc: "The Name of the Wind",
    author: "Patrick Rotfuss",
    price: 20.15,
  },
  {
    id: 7,
    name: "The Priory",
    image: "./shopping_cart/images_1/Priory.jpg",
    desc: "The Priory of the Orange Tree",
    author: "Samantha Shannon",
    price: 19.9,
  },
  {
    id: 8,
    name: "The Witcher",
    image: "./shopping_cart/images_1/Witcher.jpg",
    desc: "The Witcher",
    author: "Andrzej Sapkowski",
    price: 9.99,
  },
  {
    id: 9,
    name: "Girl",
    image: "./shopping_cart/images_1/edna-novel.jpg",
    desc: "Girl",
    author: "Edna O.Brien",
    price: 17.89,
  },
  {
    id: 10,
    name: "Real Life",
    image: "./shopping_cart/images_1/real-life.jpg",
    desc: "Real Life",
    author: " Adeline Dieudonne",
    price: 19.67,
  },
  {
    id: 11,
    name: "little scratch",
    image: "./shopping_cart/images_1/scratch_rebecca.jpg",
    desc: "little scratch",
    author: "Rebecca Watson",
    price: 20.05,
  },
  {
    id: 12,
    name: "Ready Player Two",
    image: "./shopping_cart/images_1/player-two.jpg",
    desc: "Ready Player Two",
    author: "Ernest Cline",
    price: 15.35,
  },
];

export default data;
